### ISSUE TITLE
is copying Gemfile.lock required?

### ISSUE THREAD

**Issue by takeshi-uchitane** [yohm/oacis_notebook#1]
`install.sh` tries to copy Gemfile.lock from OACIS_ROOT path to current dir.
But gems used by oacis are required after starting jupyter.
Actually, it seemed working well when I installed only gems listed in [gem "rbczmq"
gem "iruby", "~> 0.2.9"
gem "daru"
# gem "nyaplot", github: 'domitry/nyaplot', ref: 'master'

gem "nyaplot", git: 'https://github.com/domitry/nyaplot.git', ref: 'master'
gem "gnuplotrb"
gem "statsample-glm"]

**Comment by yohm** [comment]
In order to require 'config/environmnet' of OACIS, you need to install gem files required by OACIS.
So you will find an error when `require File.join( ENV['OACIS_ROOT'], 'config/environment')` in jupyter cell.

The reason why we copied Gemfile.lock is to ensure the gem version used in Jupyter is exactly same as the ones used by OACIS.

**Comment by takeshi-uchitane** [comment]
I agree it. close this issue.
